version: "3.9"

services:
  database:
    image: mongo
    restart: always
    env_file: ./environments/prod.env
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  server:
    depends_on:
      - database
    build: .
    restart: unless-stopped
    env_file: ./environments/prod.env
    command: bash -c "npm run dev"
    ports:
      - 8080:8080
    volumes:
      - .:/app

volumes:
  db:
